export ZSH="${HOME}/.local/pfke/dotfiles"

export LC_ALL=de_DE.UTF-8
export LC_MESSAGES=POSIX

export PAGER=less

export VISUAL=nvim
export EDITOR="$VISUAL"

#export TERMINAL=alacritty
export TERM="xterm-256color"

export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export RANGER_LOAD_DEFAULT_RC=FALSE

export MAKE_J_OPTION=$(nproc)
export MAKEFLAGS='-j $MAKE_J_OPTION'

eval $(systemctl --user show-environment | grep SSH_AUTH_SOCK)
export SSH_AUTH_SOCK

export XKB_DEFAULT_LAYOUT=de
export XKB_DEFAULT_MODEL=pc105
export XKB_DEFAULT_VARIANT=nodeadkeys
export WLC_REPEAT_DELAY=220
export WLC_REPEAT_RATE=25

export _JAVA_AWT_WM_NONREPARENTING=1

